## Setup

In [1]:
%pip install --upgrade plotly
%pip install --upgrade matplotlib
%pip install --upgrade seaborn

Requirement already satisfied: plotly in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (6.9.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from plotly) (2.24.0)
Requirement already satisfied: packaging in c:\users\david\appdata\roaming\python\python312\site-packages (from plotly) (25.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\david\appdata\roaming\python\python312\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=9 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (2.2.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\david\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=9 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\david\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np                      # Fast array operations and numerical computing
import pandas as pd                     # Data manipulation and analysis with DataFrames
import plotly.express as px             # Quick, high-level interactive charts
import plotly.graph_objects as go       # Fine-grained control over interactive plots
import matplotlib.pyplot as plt         # Core plotting library for static charts
import seaborn as sns                   # Statistical visualization built on matplotlib
import decimal                          # Precise, rounding-safe arithmetic for decimal numbers

In [3]:
df_data = pd.read_csv('C:/Users/David/github projects/datasets/Steam Games/games.csv', index_col=False)

In [4]:
df_data.shape

(125855, 39)

In [5]:
df_data.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...

In [6]:
print(df_data.columns)

Index(['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
       'Required age', 'Price', 'DiscountDLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies'],
      dtype='object')

## Data Exploration & Cleaning

In [7]:
df_data.columns = df_data.columns.str.replace(' ', '_') #Removing spaces from the column names

The dataset contains 125,855 unique records across 39 variables.

In [8]:
df_data.describe()

,AppID,Peak_CCU,Required_age,Price,DiscountDLC_count,About_the_game,Metacritic_url,Positive,Negative,Score_rank,Achievements,Recommendations,Notes,Average_playtime_two_weeks,Median_playtime_forever,Median_playtime_two_weeks,Developers
count,1.258550e+05,1.258550e+05,125855.000000,125855.000000,125855.000000,125855.000000,125855.000000,125855.000000,1.258550e+05,1.258550e+05,40.000000,125855.000000,1.258550e+05,1.258550e+05,125855.000000,1.258550e+05,125855.000000
mean,2.032627e+06,5.318720e+01,0.165365,4.811174,17.896826,0.535434,2.500083,0.023916,1.018182e+03,1.648786e+02,99.175000,17.922220,9.380399e+02,2.027568e+02,13.507711,1.691803e+02,14.419125
std,1.117434e+06,3.681083e+03,1.642666,12.489329,28.628518,14.328417,13.492922,1.376811,2.772782e+04,5.305001e+03,0.675107,139.696425,2.159585e+04,1.107222e+04,266.925759,1.105725e+04,290.747134
min,1.000000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,98.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,1.083495e+06,0.000000e+00,0.000000,0.590000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,99.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
50%,1.949010e+06,0.000000e+00,0.000000,2.390000,0.000000,0.000000,0.000000,0.000000,4.000000e+00,1.000000e+00,99.000000,2.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
75%,2.938410e+06,0.000000e+00,0.000000,5.545000,37.000000,0.000000,0.000000,0.000000,3.500000e+01,1.000000e+01,100.000000,19.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
max,4.437540e+06,1.013936e+06,21.000000,999.980000,100.000000,3703.000000,97.000000,100.000000,7.642084e+06,1.173003e+06,100.000000,9821.000000,4.830455e+06,3.429544e+06,20088.000000,3.429544e+06,20088.000000

In [9]:
df_data.head()

,AppID,Name,Release_date,Estimated_owners,Peak_CCU,Required_age,Price,DiscountDLC_count,About_the_game,Supported_languages,...,Average_playtime_two_weeks,Median_playtime_forever,Median_playtime_two_weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...

In [10]:
df_data.tail()

,AppID,Name,Release_date,Estimated_owners,Peak_CCU,Required_age,Price,DiscountDLC_count,About_the_game,Supported_languages,...,Average_playtime_two_weeks,Median_playtime_forever,Median_playtime_two_weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
125850,3249570,Sotsugyo Omedeto,"Mar 1, 2026",0 - 0,0,0,8.09,0,0,A survival trial game set in an all-girls scho...,...,0,0,0,0,SuperLoki,SuperLoki,"Single-player,Steam Achievements,Camera Comfor...","Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
125851,2218150,Island on cloud,"Feb 24, 2026",0 - 0,0,0,0.59,0,0,"A game with a quirky art style, resembling ani...",...,0,0,0,0,7th Ghost,7th Ghost,"Single-player,Family Sharing","Adventure,RPG",NaN,https://shared.akamai.steamstatic.com/store_it...
125852,3788650,Rosie Planet,"Mar 1, 2026",0 - 0,0,0,12.99,0,0,Jam Packed full with Videogame Rosie Planet is...,...,0,0,0,0,Connor Leary,Connor Leary,"Single-player,Full controller support,Playable...","Action,Adventure,Indie",NaN,https://shared.akamai.steamstatic.com/store_it...
125853,3509140,Fear Effect 2: Retro Helix,"Feb 27, 2026",0 - 0,0,0,9.99,0,0,Return to 2048 Hong Kong in the groundbreaking...,...,0,0,0,0,Implicit Conversions,Limited Run Games,"Single-player,Steam Achievements,Full controll...","Action,Adventure",NaN,https://shared.akamai.steamstatic.com/store_it...
125854,4247310,Project Liminal 2,"Mar 2, 2026",0 - 0,0,0,2.51,0,0,All events and characters are fictional. Any r...,...,0,0,0,0,AquaHeaven Studios,TXC,"Single-player,Steam Achievements,Full controll...","Action,Adventure,Indie",NaN,https://shared.akamai.steamstatic.com/store_it...

In [11]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       125855 non-null  int64
 1   Name                        125854 non-null  object
 2   Release_date                125855 non-null  object
 3   Estimated_owners            125855 non-null  object
 4   Peak_CCU                    125855 non-null  int64
 5   Required_age                125855 non-null  int64
 6   Price                       125855 non-null  float64
 7   DiscountDLC_count           125855 non-null  int64
 8   About_the_game              125855 non-null  int64
 9   Supported_languages         117393 non-null  object
 10  Full_audio_languages        125855 non-null  object
 11  Reviews                     125855 non-null  object
 12  Header_image                12181 non-null   object
 13  Website                     125774 non-null  object
 14  Support_url                 50520 non-null   object
 15  Support_email               55295 non-null   object
 16  Windows                     103225 non-null  object
 17  Mac                         125855 non-null  bool
 18  Linux                       125855 non-null  bool
 19  Metacritic_score            125855 non-null  bool
 20  Metacritic_url              125855 non-null  int64
 21  User_score                  4258 non-null    object
 22  Positive                    125855 non-null  int64
 23  Negative                    125855 non-null  int64
 24  Score_rank                  125855 non-null  int64
 25  Achievements                40 non-null      float64
 26  Recommendations             125855 non-null  int64
 27  Notes                       125855 non-null  int64
 28  Average_playtime_forever    23310 non-null   object
 29  Average_playtime_two_weeks  125855 non-null  int64
 30  Median_playtime_forever     125855 non-null  int64
 31  Median_playtime_two_weeks   125855 non-null  int64
 32  Developers                  125855 non-null  int64
 33  Publishers                  117406 non-null  object
 34  Categories                  116933 non-null  object
 35  Genres                      116889 non-null  object
 36  Tags                        117432 non-null  object
 37  Screenshots                 83353 non-null   object
 38  Movies                      119828 non-null  object
dtypes: bool(3), float64(2), int64(15), object(19)
memory usage: 34.9+ MB

##### Dropping and Renaming columns
Unfortunately, this dataset is not properly formatted and a number of column names have been shifted.
We will use this as an opportunity to both drop and rename columns.

Each one will also be done individually, purely for the sake to clarity. It should be stated that this could also be done simply by overwriting all header labels with a new placeholder column name at index 8, as this would shift the column names over one, creating a temporary 39th column.

In [56]:
del temp_df
del tempor

In [57]:
# First we're going to create a temporary working dataframe

temp_df = df_data.copy()

In [58]:
temp_df.drop(columns=['Required_age', 'DiscountDLC_count', 'About_the_game', 'Supported_languages', 'Header_image', 'Website', 'User_score', 'Average_playtime_forever', 'Movies'], inplace=True)

In [59]:
temp_df.head()

,AppID,Name,Release_date,Estimated_owners,Peak_CCU,Price,Full_audio_languages,Reviews,Support_url,Support_email,...,Notes,Average_playtime_two_weeks,Median_playtime_forever,Median_playtime_two_weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0.00,[],[],NaN,NaN,...,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,5.24,['English'],[],http://mangagamer.org/supipara,http://mangagamer.com,...,231,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute"
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,4.99,"['English', 'French', 'German', 'Russian']",[],https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,...,0,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec..."
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,8.99,['Korean'],['Korean'],NaN,NaN,...,0,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,4.99,['English'],['English'],https://www.realityexpanded.com/books-games,https://www.realityexpanded.com,...,0,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN

In [60]:
shifted_names = ['Supported_languages', 'Full_audio-languages', 'Website', 'Support_url', 
                 'Support_email', 'Windows', 'Mac', 'Linux', 'Metacritic_score', 'User_score', 
                 'Positive', 'Negative', 'Score_rank', 'Achievements', 'Recommendations', 
                 'Average_playtime_forever', 'Average_playtime_two_weeks', 'Median_playtime_forever', 
                 'Median_playtime_two_weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags']

temp_df = temp_df.rename(columns=dict(zip(temp_df.columns[6:], shifted_names)))

Now we will quickly check and see whether or not the dataframe looks more appropriate.

In [61]:
temp_df.head()

,AppID,Name,Release_date,Estimated_owners,Peak_CCU,Price,Supported_languages,Full_audio-languages,Website,Support_url,...,Recommendations,Average_playtime_forever,Average_playtime_two_weeks,Median_playtime_forever,Median_playtime_two_weeks,Developers,Publishers,Categories,Genres,Tags
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0.00,[],[],NaN,NaN,...,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,5.24,['English'],[],http://mangagamer.org/supipara,http://mangagamer.com,...,231,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute"
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,4.99,"['English', 'French', 'German', 'Russian']",[],https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,...,0,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec..."
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,8.99,['Korean'],['Korean'],NaN,NaN,...,0,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,4.99,['English'],['English'],https://www.realityexpanded.com/books-games,https://www.realityexpanded.com,...,0,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN

##### Correcting Data types

#### Exploring variables

In [ ]:
print(f'Are there any NaN values? {df_data.isna().values.any()}')

In [ ]:
df_data['Required_age'].value_counts()

In [ ]:
df_data.loc[df_data['Required_age'].idxmax()]

In [ ]:
df_data['Estimated_owners'].value_counts()

In [ ]:
df_data.loc[df_data['Estimated_owners'].idxmax()]

#### Identifying variables to be dropped

While many of the variables contain potentially useful information, there are a number that unfortunately are not relevant to this type of exploration and analysis.

##### Score_rank

In [ ]:
# Only 40 of the records contain a non NaN value

df_data['Score_rank'].value_counts()

##### Screenshots

In [ ]:
df_data['Screenshots'].head()

##### Support_url

In [ ]:
df_data['Support_url'].value_counts()

##### Metacritic_score

In [ ]:
df_data['Metacritic_score'].value_counts()

##### Metacritic_url

In [ ]:
df_data['Metacritic_url'].value_counts()

#### Dropping Variables

In [ ]:
# Important to note that these variables could be written in a single line, but for the purpose of showing 'Why' certains ones were dropped, I am electing to do each individually

df_final = df_data.drop(columns=['DiscountDLC_count'])  # This column isn't relevant to this exploration
df_final = df_data.drop(columns=['Header_image'])
df_final = df_data.drop(columns=['Support_url'])        # This column isn't relevant to this exploration, but might be interesting to see which websites/service host the majority of support services
df_final = df_data.drop(columns=['Support_email'])      # This column isn't relevant to this exploration, but might be interesting to see which websites/service host the majority of support services
df_final = df_data.drop(columns=['Metacritic_score'])   # Almost 97% of records do not list their Metacritic Score
df_final = df_data.drop(columns=['Metacritic_url'])     # This column isn't relevant to this exploration
df_final = df_data.drop(columns=['Screenshots'])        # This column contains image urls that are not relevant to this exploration
df_final = df_data.drop(columns=['Movies'])             # This column contains no infomation

In [ ]:
df_final.info()

#### Correcting Data Types

In [ ]:
# columns to fix
# Release_data -> Datetime
# Price -> Decimal
#